"""Add LLMCache

Revision ID: be521097f002
Revises: 6df48b8f9350
Create Date: 2026-10-06 11:26:50.569762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be521097f002'
down_revision: Union[str, Sequence[str], None] = '6df48b8f9350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('aciklama_hash', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_id'), 'llm_cache', ['id'], unique=False)
    op.create_index(op.f('ix_llm_cache_ilan_no'), 'llm_cache', ['ilan_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_cache_ilan_no'), table_name='llm_cache')
    op.drop_index(op.f('ix_llm_cache_id'), table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###
