"""Initial migration

Revision ID: ea8cf0074b0d
Revises: 
Create Date: 2026-10-06 10:31:59.797414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8cf0074b0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_logs_id'), 'fetch_logs', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('baslik', sa.String(), nullable=False),
    sa.Column('fiyat', sa.Integer(), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('il', sa.String(), nullable=False),
    sa.Column('ilce', sa.String(), nullable=True),
    sa.Column('ilan_tarihi', sa.Date(), nullable=False),
    sa.Column('seri', sa.String(), nullable=True),
    sa.Column('paket', sa.String(), nullable=True),
    sa.Column('vites', sa.String(), nullable=True),
    sa.Column('yakit', sa.String(), nullable=True),
    sa.Column('kasa_tipi', sa.String(), nullable=True),
    sa.Column('motor_hacmi', sa.String(), nullable=True),
    sa.Column('renk', sa.String(), nullable=True),
    sa.Column('kimden', sa.String(), nullable=True),
    sa.Column('agir_hasar_kayitli', sa.Boolean(), nullable=True),
    sa.Column('tramer_tutari_yapilandirilmis', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('raw_html_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ilan_no')
    )
    op.create_index(op.f('ix_listings_ilan_no'), 'listings', ['ilan_no'], unique=False)
    op.create_table('market_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('medyan', sa.Integer(), nullable=False),
    sa.Column('p25', sa.Integer(), nullable=False),
    sa.Column('p75', sa.Integer(), nullable=False),
    sa.Column('guven', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_cache_hash'), 'market_cache', ['hash'], unique=True)
    op.create_index(op.f('ix_market_cache_id'), 'market_cache', ['id'], unique=False)
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('active_hours', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watches_id'), 'watches', ['id'], unique=False)
    op.create_index(op.f('ix_watches_name'), 'watches', ['name'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('alinti', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ilan_no'], ['listings.ilan_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('fiyat', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ilan_no'], ['listings.ilan_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_snapshots_id'), 'listing_snapshots', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ilan_no'], ['listings.ilan_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_no', sa.String(), nullable=False),
    sa.Column('etiket', sa.String(), nullable=False),
    sa.Column('guven_skoru', sa.Float(), nullable=False),
    sa.Column('veri_tamlik', sa.Float(), nullable=False),
    sa.Column('hard_fails', sa.JSON(), nullable=True),
    sa.Column('artilar', sa.JSON(), nullable=True),
    sa.Column('eksiler', sa.JSON(), nullable=True),
    sa.Column('tavsiye_teklif', sa.Integer(), nullable=True),
    sa.Column('ekspertiz_kontrol_listesi', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ilan_no'], ['listings.ilan_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_id'), 'verdicts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listing_snapshots_id'), table_name='listing_snapshots')
    op.drop_table('listing_snapshots')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_watches_name'), table_name='watches')
    op.drop_index(op.f('ix_watches_id'), table_name='watches')
    op.drop_table('watches')
    op.drop_index(op.f('ix_market_cache_id'), table_name='market_cache')
    op.drop_index(op.f('ix_market_cache_hash'), table_name='market_cache')
    op.drop_table('market_cache')
    op.drop_index(op.f('ix_listings_ilan_no'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_fetch_logs_id'), table_name='fetch_logs')
    op.drop_table('fetch_logs')
    # ### end Alembic commands ###
